---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
  labels:
    {{- include "releaseLabels" . | indent 4 }}
type: Opaque
data:
# TODO - Add any secret values here.
#
# These should be key:value pairs where the key is the environmental value to
# be set and the value is the value for that environmental value, remember that
# it needs to be base64 encoded. In the example below the PASSWORD
# environmental value will be set to be example.password from the Values.
  PASSWORD: {{ .Values.example.password | b64enc }}
