---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    {{- include "releaseLabels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    {{- include "selectionLabels" . | indent 4 }}
